title: Patrick Ho
email: peiqistar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sr. Software Engineering Manager at Cadence Design Inc.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
